=== smurf667/cc2-polyglot/src/test/resources/xml/easy-in.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
	attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	targetNamespace="http://localhost/easy-in"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="data">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="items">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="firstName" use="optional"/>
											<xs:attribute type="xs:string" name="lastName" use="optional"/>
											<xs:attribute type="xs:string" name="street" use="optional"/>
											<xs:attribute type="xs:string" name="cityCode" use="optional"/>
											<xs:attribute type="xs:string" name="countryCode" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="cities">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="city" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="code"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="countries">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="country" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="code"/>
											<xs:attribute type="xs:string" name="name"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== smurf667/cc2-polyglot/src/main/resources/xml/easy1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data xmlns="http://localhost/easy-in"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://localhost/easy-in easy-in.xsd">
	<!-- straight-forward mapping example -->
	<items>
		<item firstName="fn1" lastName="ln1" street="street1" cityCode="city1" countryCode="country1" />
		<item firstName="fn2" lastName="ln2" street="street2" cityCode="city2" countryCode="country2" />
		<item firstName="fn3" lastName="ln3" street="street3" cityCode="city1" countryCode="country2" />
	</items>
	<cities>
		<city code="city1">city1</city>
		<city code="city2">city2</city>
		<city code="city3">city3</city>
	</cities>
	<countries>
		<country code="country1" name="country1" />
		<country code="country2" name="country2" />
		<country code="country3" name="country3" />
		<country code="country4" name="country4" />
		<country code="country5" name="country5" />
	</countries>
</data>

=== smurf667/cc2-polyglot/src/main/resources/xml/easy2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data xmlns="http://localhost/easy-in"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://localhost/easy-in easy-in.xsd">
	<!-- mapping gaps for city and country -->
	<items>
		<item firstName="fn1" lastName="ln1" street="street1" cityCode="unknown" countryCode="country" />
		<item firstName="fn2" lastName="ln2" street="street2" cityCode="city" countryCode="unknown" />
	</items>
	<cities>
		<city code="city">city</city>
	</cities>
	<countries>
		<country code="country" name="country" />
	</countries>
</data>
